### ISSUE TITLE
Build the new homepage

### ISSUE THREAD

**Issue by ocavue** [ocavue/rino#295]
Steps:

- [x] Add a simple home page placeholder for visitors who are not logged in. Don't consider SEO nor the content of homepage. #294
- [x] Make this homepage beautiful and meaningful. #298 #302
- [ ] Use firebase functions to serve the website #293
  - [ ] Remove netlify deployment
  - [ ] Add a new firebase APP for develop deployment
  - [ ] Build a static 404 page
- [x] Make the homepage SEO friendly
